[package]
name = "rust-fsm"
description = "A framework for building finite state machines in Rust"
repository = "https://github.com/eugene-babichenko/rust-fsm"
homepage = "https://github.com/eugene-babichenko/rust-fsm"
documentation = "https://docs.rs/rust-fsm/"
readme = "README.md"
license = "MIT"
categories = ["data-structures", "rust-patterns"]
keywords = ["fsm"]
version = "0.3.1"
authors = ["Yevhenii Babichenko"]
edition = "2018"

[badges]
travis-ci = { repository = "eugene-babichenko/rust-fsm" }

[dependencies]
rust-fsm-dsl = { path = "./rust_fsm_dsl", version = "0.3.0" }

[workspace]
members = [".", "rust_fsm_dsl"]
